/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export type GetApplicationsApplicationIdMessagesMessageIdPromtsPromtIdChanges500 = {
  error?: boolean;
  message?: string;
};
