/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */

export interface IMongoModelChange {
  /** Идентификатор изменения. */
  _id?: string;
  /** Идентификатор приложения, к которому относится изменение. */
  application?: string;
  /** Идентификатор промта, к которому относится изменение. */
  promt?: string;
  /** Тип изменения (например, 'update', 'create', 'delete'). */
  changeType?: string;
  /** Содержимое изменения. */
  content?: string;
  /** Дата и время создания изменения. */
  createdAt?: string;
}
