/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * EasyAppz API
 * API documentation for EasyAppz
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  GetApplications200,
  GetApplications401,
  GetApplications500,
  IMongoModelApplication,
  PostApplicationsApplicationIdRestart200,
  PostApplicationsApplicationIdRestart400,
  PostApplicationsApplicationIdRestart404,
  PostApplicationsApplicationIdRestart500,
  PostApplicationsBody,
  ServerErrorResponse
} from './types';

import postApplicationsApplicationIdRestartMutator from '../axios';
import type { ErrorType as PostApplicationsApplicationIdRestartErrorType } from '../axios';
import getApplicationsMutator from '../axios';
import type { ErrorType as GetApplicationsErrorType } from '../axios';
import postApplicationsMutator from '../axios';
import type { ErrorType as PostApplicationsErrorType } from '../axios';





/**
 * Возвращает список всех приложений, к которым имеет доступ аутентифицированный пользователь (req.user).
 * @summary Получить список приложений
 */
export const getApplications = (
 signal?: AbortSignal
) => {
      
      
      return getApplicationsMutator<GetApplications200>(
      {url: `/applications`, method: 'GET', signal
    },
      );
    }
  

export const getGetApplicationsQueryKey = () => {
    return [`/applications`] as const;
    }

    
export const getGetApplicationsQueryOptions = <TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApplicationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApplications>>> = ({ signal }) => getApplications(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApplicationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApplications>>>
export type GetApplicationsQueryError = GetApplicationsErrorType<GetApplications401 | GetApplications500>


export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>( options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplications>>,
          TError,
          Awaited<ReturnType<typeof getApplications>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApplications>>,
          TError,
          Awaited<ReturnType<typeof getApplications>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Получить список приложений
 */

export function useGetApplications<TData = Awaited<ReturnType<typeof getApplications>>, TError = GetApplicationsErrorType<GetApplications401 | GetApplications500>>(
 options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApplications>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApplicationsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Перезапускает указанное приложение.
 * @summary Перезапуск приложения
 */
export const postApplicationsApplicationIdRestart = (
    applicationId: string,
 signal?: AbortSignal
) => {
      
      
      return postApplicationsApplicationIdRestartMutator<PostApplicationsApplicationIdRestart200>(
      {url: `/applications/${applicationId}/restart`, method: 'POST', signal
    },
      );
    }
  

export const getPostApplicationsApplicationIdRestartMutationOptions = <TError = PostApplicationsApplicationIdRestartErrorType<BadRequestResponse | PostApplicationsApplicationIdRestart400 | PostApplicationsApplicationIdRestart404 | PostApplicationsApplicationIdRestart500 | ServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApplicationsApplicationIdRestart>>, TError, {applicationId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApplicationsApplicationIdRestart>>, TError, {applicationId: string}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


   return  { mutationFn: (data) => postApplicationsApplicationIdRestart(data.applicationId, ), ...mutationOptions} as UseMutationOptions<Awaited<ReturnType<typeof postApplicationsApplicationIdRestart>>, TError, {applicationId: string}, TContext>
}

export type PostApplicationsApplicationIdRestartMutationResult = NonNullable<Awaited<ReturnType<typeof postApplicationsApplicationIdRestart>>>
export type PostApplicationsApplicationIdRestartMutationError = PostApplicationsApplicationIdRestartErrorType<BadRequestResponse | PostApplicationsApplicationIdRestart400 | PostApplicationsApplicationIdRestart404 | PostApplicationsApplicationIdRestart500 | ServerErrorResponse>

/**
 * @summary Перезапуск приложения
 */
export const usePostApplicationsApplicationIdRestart = <TError = PostApplicationsApplicationIdRestartErrorType<BadRequestResponse | PostApplicationsApplicationIdRestart400 | PostApplicationsApplicationIdRestart404 | PostApplicationsApplicationIdRestart500 | ServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApplicationsApplicationIdRestart>>, TError, {applicationId: string}, TContext>, }
) => {

  const mutationOptions = getPostApplicationsApplicationIdRestartMutationOptions<TError, TContext>(options);

 return useMutation(mutationOptions);
}



/**
 * Создает новое приложение для аутентифицированного пользователя (req.user) на основе переданного описания.
 * @summary Создание приложения
 */
export const postApplications = (
    postApplicationsBody: PostApplicationsBody,
 signal?: AbortSignal
) => {
      
      
      return postApplicationsMutator<IMongoModelApplication>(
      {url: `/applications`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApplicationsBody, signal
    },
      );
    }

export const getPostApplicationsMutationOptions = <TError = PostApplicationsErrorType<BadRequestResponse | ServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApplications>>, TError,{data: PostApplicationsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApplications>>, TError,{data: PostApplicationsBody}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


   return  { mutationFn: (data) => postApplications(data.data, ), ...mutationOptions} as UseMutationOptions<Awaited<ReturnType<typeof postApplications>>, TError,{data: PostApplicationsBody}, TContext>
}

export type PostApplicationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApplications>>>
export type PostApplicationsMutationError = PostApplicationsErrorType<BadRequestResponse | ServerErrorResponse>

/**
 * @summary Создание приложения
 */
export const usePostApplications = <TError = PostApplicationsErrorType<BadRequestResponse | ServerErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApplications>>, TError,{data: PostApplicationsBody}, TContext>, }
) => {

  const mutationOptions = getPostApplicationsMutationOptions<TError, TContext>(options);

 return useMutation(mutationOptions);
}
